(fix): Add conditional PyYaML import for colab
Fixes AttributeError: module 'yaml' has no attribute 'FullLoader'
during `yaml.load(fp, Loader = yaml.FullLoader)`
due to outdated version of yaml module in Colab.